### ISSUE TITLE
Moving and deleting files

### ISSUE THREAD

**Issue by merijnbeeksma** [proycon/flat#121] opened 2017-10-13 09:20 UTC
'Move selected files' does not move but copy them (while there is a separate copy function).
'Delete selected files' does not delete files.

**Comment by proycon** [comment] 2017-10-13 19:34
oh? that must be a bug indeed! Might be due to the setup on ponyland rather than a FLAT issue, I'll have to investigate.

**Comment by proycon** [comment] 2017-10-17 12:31
I guess this one has lowest priority, focussing on the others first.

**Comment by proycon** [comment] 2017-10-17 19:26
can reproduce, confirmed

**Comment by proycon** [comment] 2017-10-17 19:30
It's a git issue, probably specific to the ponyland installation:

```
2017-10-17 21:25:18 - Copying /var/www/flat/live/writable/docroot/proycon/page1014.tested.tagged.folia.xml to /var/www/flat/live/writable/docroot/pub/page1014.tested.tagged.folia.xml
2017-10-17 21:25:18 - Doing git commit for /var/www/flat/live/writable/docroot/pub/page1014.tested.tagged.folia.xml -- Adding copied document
2017-10-17 21:25:18 - Doing git commit for /var/www/flat/live/writable/docroot/proycon/page1014.tested.tagged.folia.xml -- Deleting document
2017-10-17 21:25:18 - ERROR during git rm/commit of /var/www/flat/live/writable/docroot/proycon/page1014.tested.tagged.folia.xml
```

**Comment by proycon** [comment] 2017-10-17 19:34
Not a FLAT bug as-such but a permission issue on the server

**Comment by proycon** [comment] 2017-10-20 15:52
This should now hopefully be fixed on server and with proycon/foliadocserve#11 , please test

**Closed** 2017-10-23 10:19 UTC
