### ISSUE TITLE
flat completely trips

### ISSUE THREAD

**Issue by merijnbeeksma** [proycon/flat#125] opened 2017-11-01 11:20 UTC
context: one annotator gets this screen, regardless of which computer she works on (but she does NOT get this error when working from a phone). She uses Chrome.

<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABpAAAAQaCAYAAABElztWAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7H0HgCVFtfaZHDayLDlHyUEUJLMkQXISMAJGRFAQFNN7T0VMiAHMgRwkCQiSBSRnJMcNZNi8LBsm7Pzn+86p6uq+fe/cWXZW4J/v3uoT61To6rrdXdM9Datv/u2+vr5eAXq7Zktv92yZO+spyosGfaW0oaFPk1Lyiew626gOZKHhuZMgby/euwHv5BaGMVAbNb0qjH15VZXMpnZjwacyi2oqle84VKtirRHQb7PoUN0rZ+mrw69GvOq5FTWNixKLqiDt9X7nmcynqj2g3GEIKfrdddUdoqWSIUpzVg/338fQeBnC28SiGUIlUQqq/ssZcIYaLvXFqqOIcjBjPnfNWBVGU9TM0x+SzLk4LmS6hgFPYW+rXkQhQkWdaqPK9Fw9wNuYo6dPmyFNzR3KeZCGRi0mVFj7bkG39PX2yMjRnVAEdeQHAr3o4ukTSiJFWiCiX1KrgcbtC/tMeS3MS/U0hCEMYQhDGMIQhjCEIQxhCIOD1o6VpLVzaV6PNDQ26eVIszSs9sET+/oW9Mj82S9L99yJsuQSw+Rznz1MNtl0c8tVCruk6Q/08pvMdrmjvF/3NCq1RSO9KFIBMmwk0Llff7AyNNXpX0SazWpaGSroS+

Etc.

**Comment by proycon** [comment] 2017-11-01 11:32
hmm, hard to say anything about this. Seems a random HTML snippet.  

* Which user?
* What URL does she access exactly?
* Does every page present this problem?

**Comment by merijnbeeksma** [comment] 2017-11-01 13:34
- nnota
- logging in and opening documents works, it happens when she tries to add annotations
- yes

**Comment by proycon** [comment] 2017-11-01 14:06
So loading works? Does it happen when she clicks a word for annotation? Or when she submits an annotation? It's a strange problem and I can't reproduce this at all yet..

There might even be a local chrome plugin interfering in some way, try firefox instead (also a viable workaround)? Though if it's really a FLAT bug I'm of course interested in finding the cause.

**Comment by merijnbeeksma** [comment] 2017-11-01 19:00
Loading works. It happens when she clicks on a word to annotate it. She tried Explorer too, with the same result..

**Comment by proycon** [comment] 2018-01-22 11:39
Closing, seems no longer an issue/relevant?

**Closed by proycon** 2018-01-22 11:39 UTC
Labels: details needed
